### PR TITLE
Update CSS to prevent content from leaving screen

### PR DESCRIPTION
**Pull request by zwatson2001**
The goal of this PR is to prevent the bottom buttons from leaving the screen, which was happening for matrix reasoning and TOM. I applied the `instruction-small` class to these tasks and also made each of the size variables for the `image` button class slightly smaller, which changes the size of the big stimulus images since they were previously set to 3x the size of the buttons. As far as I know `image` is currently only used for the buttons in these two tasks, so buttons in other tasks shouldn't be affected. I also slightly decreased the font size used for `instruction-small` and gave it min and max values.

### CODE REVIEW

**Comment by asengupta3** [comment]
@zwatson2001 I am personally fine with these changes but I fear that it may not be solving the underlying issue of height here. Even though it might be looking fine for your device, if someone else has a different aspect ratio screen, the buttons might go out of screen again. One way to avoid this is by introducing scroll. We can either scroll the instruction container or the entire layout. But before we do that, it might be helpful to discuss with Anastasia to get an idea of what might be aesthetically better.
This is a very tricky part of web development with no winning solution. There is always going to be some compromise here but lets discuss those compromises and make it clear and document what works and what does not work.

**Comment by zwatson2001** [comment]
@asengupta3 that all sounds good, thanks for taking a look! I'd be happy to discuss what looks best, and I can leave this PR open until we make a decision.

**Comment by kachergis** [comment]
I'm pretty firm on not introducing scrolling -- not feasible for young kids. I know there's no silver bullet, but we need a solution that scales element widths based on screenwidth, and element height based on screenheight. If this is better than current, we should merge it...

**Comment by mcfrank** [comment]
I agree with George about scrolling being off the table, so scaling is the
right solution... I don't know enough about the current approach to give
good suggestions, but it seems reasonable to me to think about scaling down
the buttons for small devices.

**Comment by asengupta3** [comment]
All of that is possible except the instruction prompt size. You can always break your scaled systems by introducing a very long prompt. Regardless of how much we scale the elements, the instruction element height is always an unknown and I believe Zach is trying to fix that in this PR. Some of the buttons are probably going out of screen because of very large instructions. I think if we do not want scrolling, one way to handle that is to introduce some sort of word count limit to the instructions. That way we will know what is the maximum amount of scaling required for the fonts. The rest of the elements can be auto scaled to the screen.

**Comment by zwatson2001** [comment]
There was already some auto scaling of buttons in place (I think there are three sizes corresponding to small, medium, and large screens). This PR just makes the button smallest button size and the instructions a bit smaller. I think if we're looking for a more permanent solution then introducing a word limit per instruction trial makes sense, because very long instructions would probably be easier to understand if they were broken up with different supporting images anyway. I think I'll test and merge this for now, and continue to look out for adjustments to scaling that should be made as the tasks develop. Thank you all for your input!

**Comment by mcfrank** [comment]
I like the word limit idea, Zach. That seems like it gives us a guarantee
that we stay on the page. :)

**Pull request merged**
